### ISSUE TITLE
Small bug in readme

### ISSUE THREAD

**Issue by KasperKloster** [shipmondo/shipmondo_php_sdk#1]
In your README. The line:
` echo $client->pickupPoints($params);`

You meant:
`echo $client->getPickupPoints($params);`

Right?

**Comment by JanMSP** [comment]
Yes. Thanks for reporting. https://github.com/shipmondo/shipmondo_php_sdk/commit/bfc610dde7dde9ccb9c012cee36c84a9cbcf7806
